name: "MibooGram Docker Build"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
    inputs:
      tags:
        description: 'main version tag, example: v4'
        required: true
        default: 'v4'

jobs:
  build:
    runs-on: ubuntu-latest
    name: docker build and publish
    env:
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_REPOSITORY: ${{ vars.DOCKER_MIBOOGRAM_REPO }}
      DOCKER_TAG: ${{ github.event.inputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Buildx cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx

      - name: Download Dockerfile
        run: |
          wget -O Dockerfile https://raw.githubusercontent.com/PaiGramTeam/MibooGram/zzz/Dockerfile

      - name: Build
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --output "type=image,push=true" \
            --platform "linux/amd64,linux/arm64/v8" \
            --tag "${DOCKERHUB_REPOSITORY}:${DOCKER_TAG}" \
            -f Dockerfile \
            .
